shop/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('paypal/',include('paypal.standard.ipn.urls'))
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.index,name='index'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('producto/<int:producto_id>',views.producto,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('logout',views.logoutUsuario,name='logoutUsuario'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('pedidos',views.pedidos,name='pedidos'),
    path('pedidopagado',views.pedidopagado,name='pedidopagado')
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User

from cloudinary.models import CloudinaryField


# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    stock = models.IntegerField(default=0)
    pub_date = models.DateTimeField('fecha registro')
    #imagen = models.ImageField(upload_to='productos',blank=True,null=True)
    imagen = CloudinaryField('image',default='')
    
    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    
    def __str__(self):
        return self.telefono
    

class Pedido(models.Model):
    SOLICITADO = 'solicitado'
    PAGADO = 'pagado'
    
    ESTADO_CHOICES = (
        (SOLICITADO,'Solicitado'),
        (PAGADO,'Pagado')
    )
    
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_reg = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20,default='solicitado',choices=ESTADO_CHOICES)
    nro_recibo = models.CharField(max_length=200,default='')
    total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    
    def __str__(self):
        return str(self.fecha_reg)
    
class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete= models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    
    def __str__(self):
        return self.producto.nombre

tienda/forms.py
from django import forms
from django.forms import ModelForm

from django.contrib.auth.models import User

class ClienteForm(forms.Form):
    nombre = forms.CharField(label='Nombre',max_length=200,required=True)
    apellidos = forms.CharField(label='Apellidos',max_length=200,required=True)
    email = forms.EmailField(required=True)
    direccion = forms.CharField(widget=forms.Textarea,required=True)
    telefono = forms.CharField(max_length=20)
    usuario = forms.CharField(max_length=20,required=True)
    password = forms.CharField(widget=forms.PasswordInput)

tienda/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate

from .models import Categoria,Producto,Cliente,Pedido,PedidoDetalle
from django.contrib.auth.models import User

from tienda.carrito import Cart
from tienda.forms import ClienteForm

### PAYPAL####
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm

# Create your views here.
def index(request):
    listaProductos = Producto.objects.all()
    listaCategorias = Categoria.objects.all()
    context = {
        'productos': listaProductos,
        'categorias': listaCategorias
    }
    return render(request,'index.html',context)

def productosPorCategoria(request,categoria_id):
    objCategoria = Categoria.objects.get(pk=categoria_id)
    listaCategorias = Categoria.objects.all()
    listaProductos = objCategoria.producto_set.all()
    context = {
        'productos':listaProductos,
        'categorias':listaCategorias
    }
    return render(request,'index.html',context)

def producto(request,producto_id):
    objProducto = Producto.objects.get(pk=producto_id)
    context = {
        'producto':objProducto
    }
    return render(request,'producto.html',context)

def carrito(request):
    return render(request,'carrito.html')

def agregarCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.add(objProducto,1)
    print(request.session.get("cart"))
    return render(request,'carrito.html')

def eliminarProductoCarrito(request,producto_id):
    objProducto = Producto.objects.get(id=producto_id)
    carritoProducto = Cart(request)
    carritoProducto.remove(objProducto)
    return render(request,'carrito.html')

def limpiarCarrito(request):
    carritoProducto = Cart(request)
    carritoProducto.clear()
    return render(request,'carrito.html')

########## VISTAS PARA LOGIN Y REGISTRO DE USUARIOS

def loginUsuario(request):
    context = {}
    if request.method == 'POST':
        #LOGIN DE USUARIOS
        dataUsuario = request.POST['usuario']
        dataPassword = request.POST['password']
        
        usuarioAuth = authenticate(request,username=dataUsuario,password=dataPassword)
        if usuarioAuth is not None:
            login(request,usuarioAuth)
            return redirect('/cuenta')
        else:
            context = {
                'error':'datos incorrectos'
            }
    return render(request,'login.html',context)

def cuentaUsuario(request):
    try:
        clienteEditar = Cliente.objects.get(usuario = request.user)
        dataCliente = {'nombre':request.user.first_name,
                    'apellidos':request.user.last_name,
                    'email':request.user.email,
                    'direccion':clienteEditar.direccion,
                    'telefono':clienteEditar.telefono,
                    'usuario':request.user.username}
    except:
        dataCliente = {'nombre':request.user.first_name,
                    'apellidos':request.user.last_name,
                    'email':request.user.email,
                    'usuario':request.user.username}
    
    frmCliente = ClienteForm(dataCliente)
    
    context = {
        'frmCliente':frmCliente
    }
    return render(request,'cuenta.html',context)

def crearUsuario(request):
    if request.method == 'POST':
        dataUsuario = request.POST['nuevoUsuario']
        dataPassword = request.POST['nuevoPassword']
        
        nuevoUsuario = User.objects.create_user(username=dataUsuario,password=dataPassword)
        login(request,nuevoUsuario)
        return redirect('/cuenta')
    
def actualizarCliente(request):
    mensaje =  ""
    if request.method == 'POST':
        frmCliente = ClienteForm(request.POST)
        if frmCliente.is_valid():
           #ACTUALIZAMOS EL USUARIO Y CLIENTE
           dataCliente = frmCliente.cleaned_data
           print(dataCliente)
           
           #ACTUALIZAMOS USUARIO
           actUsuario = User.objects.get(pk=request.user.id)
           actUsuario.first_name = dataCliente["nombre"]
           actUsuario.last_name = dataCliente["apellidos"]
           actUsuario.email = dataCliente["email"]
           actUsuario.save()
           
           try:
                actCliente = Cliente.objects.get(usuario = request.user)
                actCliente.direccion = dataCliente["direccion"]
                actCliente.telefono = dataCliente["telefono"]
                actCliente.save()
           except:
                nuevoCliente = Cliente()
                nuevoCliente.usuario = actUsuario
                nuevoCliente.direccion = dataCliente["direccion"]
                nuevoCliente.telefono = dataCliente["telefono"]
                nuevoCliente.save()
           
           mensaje =  "DATOS ACTUALIZADOS"
        else:
           mensaje = "ERROR AL ACTUALIZAR LOS DATOS"
    context = {
            'mensaje':mensaje,
            'frmCliente':frmCliente
        }
    return render(request,'cuenta.html',context)
        
def logoutUsuario(request):
    logout(request)
    return render(request,'login.html')


###################################################
######### PEDIDOS #################
def registrarPedido(request):
    if request.user.id is not None:
        #REGISTRA EL PEDIDO
        clientePedido = Cliente.objects.get(usuario=request.user)
        nuevoPedido = Pedido()
        nuevoPedido.cliente = clientePedido
        nuevoPedido.save()
        
        #REGISTRAMOS EL DETALLE DEL PEDIDO
        carritoPedido = request.session.get("cart")
        totalPedido = 0
       
        for key,value in carritoPedido.items():
            
            productoPedido = Producto.objects.get(pk=value["producto_id"])
            
            nuevoPedidoDetalle = PedidoDetalle()
            nuevoPedidoDetalle.pedido = nuevoPedido
            nuevoPedidoDetalle.producto = productoPedido
            nuevoPedidoDetalle.cantidad = int(value["cantidad"])
            nuevoPedidoDetalle.save()
            totalPedido += float(value["cantidad"]) * float(productoPedido.precio)
            
        nuevoPedido.total = totalPedido
        nuevoPedido.save()
        ## CREAMOS BOTON DE PAGO PARA PAYPAL
        request.session['paypal_pid'] =  nuevoPedido.id
        host = request.get_host()
        paypal_datos = {
            'business': settings.PAYPAL_RECEIVER_EMAIL,
            'amount': totalPedido,
            'item_name':'PEDIDO # ' + str(nuevoPedido.id),
            'invoice': str(nuevoPedido.id),
            'notify_url': 'http://' + host + '/' + 'paypal-ipn',
            'return_url': 'http://' + host + '/' + 'pedidopagado'
        }
        
        formPedidoPaypal = PayPalPaymentsForm(initial=paypal_datos)
        
        context = {
            'pedido':nuevoPedido,
            'formpaypal':formPedidoPaypal
        } 
        carrito = Cart(request)
        carrito.clear()
        return render(request,'pago.html',context)
    else:
        return redirect('/login')

    
def pedidopagado(request):
    pedidoID = request.session.get("paypal_pid")
    print(pedidoID)
    pedidoEditar = Pedido.objects.get(pk=pedidoID)
    pedidoEditar.estado = 'pagado'
    pedidoEditar.save()
    
    return redirect('/pedidos')
    
    
def pedidos(request):
    context = {}
    if request.user.id is not None:
        #retorna los pedidos del cliente logueado
        clienteFiltro = Cliente.objects.get(usuario=request.user) 
        listaPedidos = Pedido.objects.filter(cliente=clienteFiltro)
        context = {
            'pedidos':listaPedidos
        }
    else:
        return redirect('/login')
    
    return render(request,'pedidos.html',context)
    
###################################

tienda/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
<div class="cont maincont">
    <h1 class="maincont-ttl">CARRITO DE COMPRAS</h1>
    <div class="page-styling">

    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="product.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">CATEGORIA</a>
                        </p>
                        <h3><a href="product.html">{{ value.nombre }}</a></h3>
                    </div><!--
                    No Space
                --><div class="prod-li-prices">
                        <div class="prod-li-price-wrap">
                            <p>Price</p>
                            <p class="prod-li-price">${{ value.precio }}</p>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{ value.cantidad }}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{ value.total }}</p>
                        </div>
                    </div><!--
                    No Space
                    --></div>
                    <div class="prod-li-info">
                        <p class="prod-li-add">
                            <a href="{% url 'tienda:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>ELIMINAR</span></a>
                        </p>
                    </div>
                </div>
        </article>
        {% endfor %}
        
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <a href="{% url 'tienda:limpiarCarrito' %}" class="checkout-button button">limpiar el Carrito</a>
        </div>
        <div class="cart-collaterals">
            <a href="{%url 'tienda:registrarPedido' %}" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">$510.00</p>
            </div>
        </div>
    </div>


</div>
</div>
{% endblock %}

tienda/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}

<main id="main" class="site-main">
    <div class="cont maincont">
        <h1 class="maincont-ttl">Cuenta de Cliente</h1>
        <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos de Cliente</h2>
                    <h3>{{mensaje}}</h3>
                    <form method="post" action="{% url 'tienda:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{ frmCliente.as_p }}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
    </div>
</main>
{% endblock %}

tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="section-wrap-withsb">
    <aside class="blog-sb-widgets section-sb" id="section-sb">
        <div class="theiaStickySidebar">
            <p class="section-filter-toggle filter_hidden">
                <a href="#" id="section-filter-toggle-btn">Show Filter</a>
            </p>
            <div class="section-filter">
                <div class="section-filter">
                    <div class="blog-sb-widget multishopcategories_widget">
                        <h3 class="widgettitle">Categorias</h3>
                        <div class="section-sb-current">
                            <ul class="section-sb-list">
                                {% for categoria in categorias %} 
                                <li>
                                    <a href="{% url 'tienda:productosPorCategoria' categoria.id  %}"><span class="section-sb-label">{{ categoria.nombre }} <span class="count">{{ categoria.producto_set.all.count}}</span></span></a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </aside>        <div class="section-list-withsb" id="section-list-withsb">
    <div class="theiaStickySidebar">
        
        <div class="row prod-items prod-items-2">
            {% for producto in productos %}
            <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
                <div class="sectgl prod-i">
                    <div class="prod-i-top">
                        <a class="prod-i-img" href="{% url 'tienda:producto' producto.id  %}">
                            <img src="{{ producto.imagen.url }}" alt="">
                        </a>
                    </div>
                    <div class="prod-i-bot">
                        <div class="prod-i-info">
                            <p class="prod-i-price">${{ producto.precio }}</p>
                            <p class="prod-i-categ"><a href="catalog-gallery.html">{{ producto.categoria.nombre }}</a></p>
                        </div>
                        <h3 class="prod-i-ttl"><a href="{% url 'tienda:producto' producto.id  %}">{{ producto.nombre }}</a></h3>
                    </div>
                </div>
            </article>
            {% endfor %}            
        
        </div>
        <ul class="page-numbers">
            <li><span class="page-numbers current">1</span></li>
            <li><a class="next page-numbers" href="#"><i class="fa fa-angle-right"></i></a></li>
        </ul>
    </div><!-- .theiaStickySidebar -->
</div><!-- .section-list-withsb -->
</div><!-- .section-wrap-withsb -->

{% endblock %}

tienda/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>MULTISHOP</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">
    <div class="container-fluid page-styling site-header-before">
        <div class="row">
            <div class="col-lg-4">
                <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                    <li>
                        <p class="links_list-value">
                            <a href="http://facebook.com" target="_blank" rel="nofollow">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </p>
                    </li>
                    <li>
                        <p class="links_list-value">
                            <a href="mailto:email@email.com" target="_blank" rel="nofollow">
                                <i class="fa fa-paper-plane"></i>
                            </a>
                        </p>
                    </li>
                </ul>
            </div>
            <div class="col-lg-8">
                <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                    <li>
                        <p class="links_list-label">
                           Dirección
                        </p>
                        <p class="links_list-value">
                            <a href="http://maps.google.com" target="_blank" rel="nofollow">Calle normal 123, Perú</a>
                        </p>
                    </li>
                    <li>
                        <p class="links_list-label">
                            Contactos
                        </p>
                        <p class="links_list-value">
                            <a href="mailto:support@email.com">fashionstore@gmail.com</a>
                        </p>
                    </li>
                    <li>
                        <p class="links_list-label">
                            Telefono
                        </p>
                        <p class="links_list-value">
                            <a href="tel:4785929899">(478)-592-9899</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <div class="site-header">

        <p class="h-logo">
            <a href="{% url 'tienda:index' %}"><img src="https://res.cloudinary.com/dd9ad40qm/image/upload/v1643077505/cesarmaytashop/logo_okxlai.png" alt="MultiShop"></a>
        </p><!--
    No Space
    --><div class="h-shop">

        <form method="get" action="#" class="h-search" id="h-search">
            <input type="text" placeholder="Search...">
            <button type="submit"><i class="ion-search"></i></button>
        </form>

    </div><!--
    No Space
    --><div class="mainmenu">

        <nav id="h-menu" class="h-menu">
            <ul>
                <li>
                    <a href="{% url 'tienda:loginUsuario' %}">LOGIN</a>
                </li>
                <li>
                    <a href="{% url 'tienda:pedidos' %}">PEDIDOS</a>
                </li>
                <li>
                    <a href="{% url 'tienda:logoutUsuario' %}">LOGOUT</a>
                </li>
                <li>
                    <a href="{% url 'tienda:carrito' %}">CARRITO</a>
                </li>
                
            </ul>
        </nav>

    </div><!--
    No Space
--></div>


    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
                    {%block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->

    <div class="container-fluid blog-sb-widgets page-styling site-footer">
        <div class="row">
            <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
                <a href="index.html" class="f-logo">
                    <img src="https://res.cloudinary.com/dd9ad40qm/image/upload/v1643077505/cesarmaytashop/logo_okxlai.png" alt="">
                </a>
                <p>DEMO DE TIENDA ONLINE CON DJANGO</p>
                <button class="btn callback">CONTRATAME</button>
            </div>
        </div>
    </div>
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

tienda/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<main id="main" class="site-main">
    <div class="cont maincont">
        <h1 class="maincont-ttl">Registro / Login</h1>
        <ul class="b-crumbs">
            <li><a href="{% url 'tienda:index' %}">Inicio</a></li>
            <li>Registro &amp; Login</li>
        </ul>                                                <article class="page-cont">
        <div class="page-styling">


            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Login</h2>
                    <form method="post" action="{% url 'tienda:loginUsuario' %}" class="login">
                        {% csrf_token %}
                        <p>
                            <label for="username">E-mail <span class="required">*</span></label>
                            <input type="text" id="username" name="usuario">
                        </p>
                        <p>
                            <label for="password">Password <span class="required">*</span></label>
                            <input type="password" id="password" name="password">
                        </p>
                        <p class="auth-submit">
                            <input type="submit" value="Login">
                            <input type="checkbox" id="rememberme" value="forever">
                            
                            <label for="rememberme">Recordar</label>
                        </p>
                        <p>
                            <label for="alert-danger"> {{error}}</label>
                        </p>
                        <p class="auth-lost_password">
                            <a href="#">No te acuerdas tu password?</a>
                        </p>
                    </form>
                </div>
                <div class="auth-col">
                    <h2>Nuevo Usuario</h2>
                    <form method="post" action="{% url 'tienda:crearUsuario' %}" class="register">
                        {% csrf_token %}
                        <p>
                            <label for="reg_email">Email <span class="required">*</span></label>
                            <input type="email" id="reg_email" name="nuevoUsuario">
                        </p>
                        <p>
                            <label for="reg_password">Password <span class="required">*</span></label>
                            <input type="password" id="reg_password" name="nuevoPassword">
                        </p>
                        <p class="auth-submit">
                            <input type="submit" value="Registro">
                        </p>
                    </form>
                </div>
            </div>


        </div>
    </article>
    </div>
</main>
{% endblock %}

tienda/templates/pago.html
{% extends 'layout.html' %}
{% block content %}
<main id="main" class="site-main">
    <div class="cont maincont">
        <h1 class="maincont-ttl">CLIENTE</h1>
        <div class="page-styling">
            <div class="auth-wrap">
                    <h3>Pedido Nro : {{ pedido.id }} - FECHA : {{ pedido.fecha_reg }}</h3>
                    <div class="woocommerce prod-litems section-list">
                        {% for pd in pedido.pedidodetalle_set.all %}
                        <article class="prod-li sectls">
                            <div class="prod-li-inner">
                                <a href="product.html" class="prod-li-img">
                                    <img src="{{ pd.producto.imagen.url }}" alt="">
                                </a>
                                <div class="prod-li-cont">
                                    <div class="prod-li-ttl-wrap">
                                        <p>
                                            <a href="#">{{ pd.producto.categoria.nombre }}</a>
                                        </p>
                                        <h3><a href="product.html">{{ pd.producto.nombre }}</a></h3>
                                    </div><!--
                                    No Space
                                --><div class="prod-li-prices">
                                        <div class="prod-li-price-wrap">
                                            <p>Price</p>
                                            <p class="prod-li-price">${{ pd.producto.precio }}</p>
                                        </div>
                                        <div class="prod-li-qnt-wrap">
                                            <p class="qnt-wrap prod-li-qnt">
                                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                                <input type="text" value="{{ pd.cantidad }}">
                                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                            </p>
                                        </div>
                                    </div><!--
                                    No Space
                                    --></div>
                                </div>
                        </article>
                       
                        {% endfor %}
                        
            </div>
        </div>
        
        <div class="cart-actions">
            
            <div class="cart-collaterals">
                {{ formpaypal.render }}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">{{ pedido.total }}</p>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

tienda/templates/top.html
<div class="section-top">

    <h1 class="maincont-ttl">Shop</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Catalog - Gallery</li>
    </ul>
    <div class="section-top-sort">
        <div class="section-view">
            <p>View</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-view-ttl">Gallery</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="catalog-list.html">List</a>
                    </li>
                    <li class="active">
                        <a href="catalog-gallery.html">Gallery</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="section-sort">
            <p>Sort</p>
            <div class="dropdown-wrap">
                <p class="dropdown-title section-sort-ttl">Newness</p>
                <ul class="dropdown-list">
                    <li>
                        <a href="#">Popularity</a>
                    </li>
                    <li>
                        <a href="#">Average rating</a>
                    </li>
                    <li class="active">
                        <a href="#">Newness</a>
                    </li>
                    <li>
                        <a href="#">Price: low to high</a>
                    </li>
                    <li>
                        <a href="#">Price: high to low</a>
                    </li>
                </ul>
            </div>
        </div>
        <form method="post" class="products-per-page">
            <p>Per Page</p>
            <select>
                <option value="12" selected="selected">12</option>
                <option value="24">24</option>
                <option value="48">48</option>
                <option value="-1">All</option>
            </select>
        </form>
    </div>
</div>